spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jxwx?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 8013
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      # 初始连接数
      initial-size: 5
      # 最小空闲数
      min-idle: 5
      # 最大活跃数
      max-total: 20
      # 配置获取连接等待超时的时间(毫秒)
      max-wait-millis: 60000
      # 配置间隔多久才进行一次检测,并关闭空闲的连接,
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000

# jpa设置
  jpa:
    database: mysql
    # 展示查询sql语句
    show-sql: true
    hibernate:
      # jpa策略: update为更新,create为重新删库
      ddl-auto: update
      # 不加这句默认为myisam引擎，无法生成外键，需配置为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# 日志打印
logging:
  # 路径
  path: logs
  # 日志文件名，如果不配置，默认文件名为spring.log
  file: debug.log
  level:
    # 日志水平，在运行状态下输出日志
    root: info
